### ISSUE TITLE
Reminder for File Modification Later in the Development Cycle

### ISSUE THREAD

**Issue by LilCSharp** [googleinterns/step13-2020#15]
### Issue summary

**When Alicia completes the user page, the html must be copied over to a .jsp file to use blobstore.**

Blobstore can only work when implemented with a .jsp file. Luckily, the image upload function only needs to be applied in one place, and that place is the user page.

**Comment by wu-haotian** [comment]
Hey Caleb - it's a good habit to use Issues to track the TODOs for the project. I would suggest to do one of the following:

1, Assign the Issue to yourself so other people don't need to worry about this
or
2, (Recommended) Assign the Issue to Alicia, because "Alicia completes the user page" is the prerequisite for this Issue, and Alicia should assign the Issue back to you once she "completes the user page".
